language: java
jdk:
  - openjdk8

branches:
  only:
    - master # master브랜치에 push될 떄 Travis CI 수행

before_install: # 권한을 주어야 실행 가능
  - chmod +x gradlew

# Travis CI 서버 Home
cache: # 캐시를 이용해 같은 의존성은 한번만 받도록 설정
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: './gradlew clean build' # script: master 브랜치에 푸시되었을 때 수행하는 명령어

# Travis CI에서 빌드해 만든 Jar파일을 S3에 올릴 수 있도록 코드 추가
before_deploy: #Travis CI는 특정 파일만 업로드 불가. 디렉토리 단위로만 업로드 가능.
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * #before-deploy로 이동 후 전체 압축
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/wandu-springboot-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY
    bucket: wandu-springboot-build # S3 버킷
    region: ap-northeast-2
    skin_cleanup: true
    acl: private # zip 파일 접근을 private로 함
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY
    bucket: wandu-springboot-build # S3 버킷
    key: wandu-springboot-webservice.zip
    bundle_type: zip
    application: wandu-springboot-webservice
    deployment_group: wandu-springboot-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행완료시 메일로 알림
notifications:
  email:
    recipients:
      - conpub.info@gmail.com
